import type { RedditPostInput } from "./types";

/**
 * Hardcoded OSINT-style corpus for demo. Replace with Reddit API ingest later.
 * Dates spread across ~120 days; mix of benign, noisy, and concerning (incl. coded language).
 *
 * `redditScore` / `numComments` mimic Reddit API fields (input only).
 * Risk tier and 0–10 risk score are NOT here — they come from `lib/risk-engine.ts` at runtime.
 */
export const SEED_POSTS: RedditPostInput[] = [
  {
    id: "seed-001",
    createdAt: "2025-12-20T14:22:00.000Z",
    subreddit: "army",
    author: "throwaway_AC",
    title: "PCS to Hood next month — housing tips?",
    body: "First duty station as 11B. Looking at Killeen vs on-post. Any areas to avoid for commute?",
    permalink: "/r/army/comments/demo001",
    redditScore: 89,
    numComments: 34,
  },
  {
    id: "seed-002",
    createdAt: "2025-12-21T09:15:00.000Z",
    subreddit: "FortHood",
    author: "central_tex_lurker",
    title: "Gate 6 line today",
    body: "Usual Tuesday backup or something else? Saw extra MPs but might be routine.",
    permalink: "/r/FortHood/comments/demo002",
    redditScore: 12,
    numComments: 8,
  },
  {
    id: "seed-003",
    createdAt: "2025-12-22T18:40:00.000Z",
    subreddit: "Killeen",
    author: "anon_observer_tx",
    title: "Helicopters low over WS Young",
    body: "Three birds, dark, around 6:45pm. Not news choppers. Anyone know if exercise?",
    permalink: "/r/Killeen/comments/demo003",
    redditScore: 45,
    numComments: 22,
  },
  {
    id: "seed-004",
    createdAt: "2025-12-23T11:05:00.000Z",
    subreddit: "Militaryfaq",
    author: "dependa_questions",
    title: "Tricare referral off post near Hood?",
    body: "Spouse needs PT — closest in-network off post?",
    permalink: "/r/Militaryfaq/comments/demo004",
    redditScore: 6,
    numComments: 4,
  },
  {
    id: "seed-005",
    createdAt: "2025-12-24T20:30:00.000Z",
    subreddit: "texas",
    author: "roadtrip2025",
    title: "I-35 rest stop north of Austin",
    body: "Convoy of humvees with covered trailers — cool to see. Happy holidays.",
    permalink: "/r/texas/comments/demo005",
    redditScore: 120,
    numComments: 55,
  },
  {
    id: "seed-006",
    createdAt: "2025-12-26T07:12:00.000Z",
    subreddit: "OSINT",
    author: "plane_spotter_01",
    title: "Unusual tail numbers at GRK?",
    body: "Two aircraft patterns consistent with VIP support; cross-referencing NOTAMs. Fort Hood AOI discussion in comments.",
    permalink: "/r/OSINT/comments/demo006",
    redditScore: 210,
    numComments: 98,
  },
  {
    id: "seed-007",
    createdAt: "2025-12-28T15:00:00.000Z",
    subreddit: "FortHood",
    author: "hood_local_news",
    title: "Community event — III Corps band",
    body: "Public concert downtown Killeen Saturday. Family friendly.",
    permalink: "/r/FortHood/comments/demo007",
    redditScore: 28,
    numComments: 9,
  },
  {
    id: "seed-008",
    createdAt: "2025-12-29T22:18:00.000Z",
    subreddit: "army",
    author: "angry_bucket",
    title: "Leadership always changing movement times",
    body: "Another 0400 shake for no reason. Vent only.",
    permalink: "/r/army/comments/demo008",
    redditScore: 340,
    numComments: 112,
  },
  {
    id: "seed-009",
    createdAt: "2025-12-30T13:45:00.000Z",
    subreddit: "Killeen",
    author: "watch_the_line",
    title: "Delivery trucks backed up at commercial gate",
    body: "Vendor said new credential checks. Long wait for contractors.",
    permalink: "/r/Killeen/comments/demo009",
    redditScore: 19,
    numComments: 11,
  },
  {
    id: "seed-010",
    createdAt: "2026-01-02T16:20:00.000Z",
    subreddit: "CredibleDefense",
    author: "geo_hints",
    title: "Discussion: training throughput at large CONUS posts",
    body: "Comment thread maps unit rotations to public calendar events near Hood — speculative but detailed.",
    permalink: "/r/CredibleDefense/comments/demo010",
    redditScore: 156,
    numComments: 67,
  },
  {
    id: "seed-011",
    createdAt: "2026-01-04T09:55:00.000Z",
    subreddit: "FortHood",
    author: "shadow_coordinate",
    title: "Meetup for ‘fantasy league’ draft — bring the pigskin",
    body: "Draft at the usual spot behind the strip. If weather is bad we move the party to the warehouse on Industrial. Football talk only — keep jerseys at home. PS: someone bring the ‘special’ ice for the cooler.",
    permalink: "/r/FortHood/comments/demo011",
    redditScore: 3,
    numComments: 6,
  },
  {
    id: "seed-012",
    createdAt: "2026-01-05T19:40:00.000Z",
    subreddit: "Killeen",
    author: "late_shift_driver",
    title: "Flashing blue lights by tank crossing",
    body: "Looked like exercise lanes closed. MP presence heavier than normal.",
    permalink: "/r/Killeen/comments/demo012",
    redditScore: 22,
    numComments: 14,
  },
  {
    id: "seed-013",
    createdAt: "2026-01-07T12:10:00.000Z",
    subreddit: "army",
    author: "SIGNAL_dump_account",
    title: "Anyone else hear comms testing on family day frequencies?",
    body: "Probably benign but pattern was weird — intermittent coded callsigns referencing landmarks on post.",
    permalink: "/r/army/comments/demo013",
    redditScore: 44,
    numComments: 31,
  },
  {
    id: "seed-014",
    createdAt: "2026-01-08T21:33:00.000Z",
    subreddit: "texas",
    author: "railfan_TX",
    title: "Military railcars spotted Temple line",
    body: "Photographed. Not classified; public crossing. Could correlate with unit moves.",
    permalink: "/r/texas/comments/demo014",
    redditScore: 78,
    numComments: 29,
  },
  {
    id: "seed-015",
    createdAt: "2026-01-10T08:00:00.000Z",
    subreddit: "news",
    author: "reuters_mirror_bot",
    title: "Army announces readiness exercise at central Texas installation",
    body: "Official statement — low public detail. Local subs discussing timing.",
    permalink: "/r/news/comments/demo015",
    redditScore: 890,
    numComments: 210,
  },
  {
    id: "seed-016",
    createdAt: "2026-01-12T17:25:00.000Z",
    subreddit: "FortHood",
    author: "new_to_area_2026",
    title: "Is Copeland safe?",
    body: "Renting near Clear Creek. Crime stats look ok?",
    permalink: "/r/FortHood/comments/demo016",
    redditScore: 15,
    numComments: 20,
  },
  {
    id: "seed-017",
    createdAt: "2026-01-14T23:50:00.000Z",
    subreddit: "OSINT",
    author: "username_overlap_hunter",
    title: "Cross-platform handle similarity — III Corps event",
    body: "Three accounts with stylometric overlap discussing motorcade timing. Could be coincidence; worth correlation.",
    permalink: "/r/OSINT/comments/demo017",
    redditScore: 95,
    numComments: 41,
  },
  {
    id: "seed-018",
    createdAt: "2026-01-16T10:15:00.000Z",
    subreddit: "Killeen",
    author: "bakery_worker_am",
    title: "Road closure Wednesday?",
    body: "City site says utility work; workers saw unmarked SUVs staging near cordon.",
    permalink: "/r/Killeen/comments/demo018",
    redditScore: 8,
    numComments: 5,
  },
  {
    id: "seed-019",
    createdAt: "2026-01-18T14:02:00.000Z",
    subreddit: "army",
    author: "vet_2012",
    title: "Remember MWR block leave policies?",
    body: "Old timer question — not Hood specific.",
    permalink: "/r/army/comments/demo019",
    redditScore: 21,
    numComments: 12,
  },
  {
    id: "seed-020",
    createdAt: "2026-01-20T19:18:00.000Z",
    subreddit: "FortHood",
    author: "coded_thread_main",
    title: "Pick up party supplies for the ‘big game’",
    body: "Need 4 of the fireworks cakes from last time — you know the ones that really pop off — meet behind the stadium lot after midnight when security rotates. Bring cash only. Coach wants the playbook delivered before the weekend parade route is final.",
    permalink: "/r/FortHood/comments/demo020",
    redditScore: 2,
    numComments: 3,
  },
  {
    id: "seed-021",
    createdAt: "2026-01-22T11:45:00.000Z",
    subreddit: "CredibleDefense",
    author: "open_source_mapper",
    title: "Geo-tagged photos from ranges near Hood",
    body: "User crop boxes removed EXIF but reflections show identifiable berms — weak PERSEC.",
    permalink: "/r/CredibleDefense/comments/demo021",
    redditScore: 88,
    numComments: 36,
  },
  {
    id: "seed-022",
    createdAt: "2026-01-24T16:30:00.000Z",
    subreddit: "Killeen",
    author: "citizen_journal",
    title: "School delay — unrelated?",
    body: "Fog; also heard training noise south of post. Probably unrelated.",
    permalink: "/r/Killeen/comments/demo022",
    redditScore: 33,
    numComments: 7,
  },
  {
    id: "seed-023",
    createdAt: "2026-01-26T09:20:00.000Z",
    subreddit: "army",
    author: "throwaway_signal",
    title: "Anyone track public flight trackers near Hood?",
    body: "ADSB anomalies during VIP week — educational only.",
    permalink: "/r/army/comments/demo023",
    redditScore: 67,
    numComments: 45,
  },
  {
    id: "seed-024",
    createdAt: "2026-01-28T13:00:00.000Z",
    subreddit: "FortHood",
    author: "family_frustrated",
    title: "DEERS appointment nightmare",
    body: "Pure admin vent.",
    permalink: "/r/FortHood/comments/demo024",
    redditScore: 11,
    numComments: 18,
  },
  {
    id: "seed-025",
    createdAt: "2026-01-30T20:05:00.000Z",
    subreddit: "OSINT",
    author: "aggregator_bot_test",
    title: "Spike in Hood-related keyword volume (7d)",
    body: "Automated chart; includes benign + security-related clusters.",
    permalink: "/r/OSINT/comments/demo025",
    redditScore: 55,
    numComments: 19,
  },
  {
    id: "seed-026",
    createdAt: "2026-02-02T08:40:00.000Z",
    subreddit: "Militaryfaq",
    author: "new_soldier_help",
    title: "Clearing CIF before PCS from Hood",
    body: "Checklist thread.",
    permalink: "/r/Militaryfaq/comments/demo026",
    redditScore: 24,
    numComments: 15,
  },
  {
    id: "seed-027",
    createdAt: "2026-02-04T22:15:00.000Z",
    subreddit: "texas",
    author: "storm_chaser_central",
    title: "Lightning delay at HS football — helicopters still up?",
    body: "Unrelated military question in comments about Hood ops noise.",
    permalink: "/r/texas/comments/demo027",
    redditScore: 41,
    numComments: 16,
  },
  {
    id: "seed-028",
    createdAt: "2026-02-06T10:00:00.000Z",
    subreddit: "FortHood",
    author: "supply_chain_watcher",
    title: "Civilian logistics contract award — public notice",
    body: "FOIA-adjacent discussion; timing of deliveries debated.",
    permalink: "/r/FortHood/comments/demo028",
    redditScore: 7,
    numComments: 9,
  },
  {
    id: "seed-029",
    createdAt: "2026-02-08T15:30:00.000Z",
    subreddit: "Killeen",
    author: "ring_doorbell_archive",
    title: "Weird car photographing housing near TJ Mills",
    body: "Plate obscured. Could be anything; neighbors uneasy.",
    permalink: "/r/Killeen/comments/demo029",
    redditScore: 52,
    numComments: 28,
  },
  {
    id: "seed-030",
    createdAt: "2026-02-10T18:00:00.000Z",
    subreddit: "CredibleDefense",
    author: "thread_crosslink",
    title: "Repost: III Corps social + movement correlation thread",
    body: "Links multiple subs; discusses senior leader travel windows inferred from open sources.",
    permalink: "/r/CredibleDefense/comments/demo030",
    redditScore: 142,
    numComments: 61,
  },
  {
    id: "seed-031",
    createdAt: "2026-02-12T12:00:00.000Z",
    subreddit: "army",
    author: "AIT_student_gripe",
    title: "DFAC hours Fort Sam vs Hood?",
    body: "Wrong post but mention Hood.",
    permalink: "/r/army/comments/demo031",
    redditScore: 9,
    numComments: 6,
  },
  {
    id: "seed-032",
    createdAt: "2026-02-14T21:45:00.000Z",
    subreddit: "FortHood",
    author: "valentine_meet",
    title: "Best restaurant Copperas Cove?",
    body: "Date night advice.",
    permalink: "/r/FortHood/comments/demo032",
    redditScore: 30,
    numComments: 25,
  },
  {
    id: "seed-033",
    createdAt: "2026-02-16T09:30:00.000Z",
    subreddit: "OSINT",
    author: "pattern_analyst",
    title: "Synthetic recap: Fort Hood AOI chatter (demo corpus)",
    body: "Teaching example — do not use for real ops.",
    permalink: "/r/OSINT/comments/demo033",
    redditScore: 20,
    numComments: 8,
  },
  {
    id: "seed-034",
    createdAt: "2026-02-18T14:20:00.000Z",
    subreddit: "Killeen",
    author: "conspiracy_adjacent",
    title: "Black SUVs downtown — again",
    body: "Could be feds, could be contractors. Speculation heavy.",
    permalink: "/r/Killeen/comments/demo034",
    redditScore: 14,
    numComments: 33,
  },
  {
    id: "seed-035",
    createdAt: "2026-02-20T11:11:00.000Z",
    subreddit: "FortHood",
    author: "range_schedule_guess",
    title: "Articulating vs Benning field noise comparison",
    body: "Includes approximate timing inferred from sound.",
    permalink: "/r/FortHood/comments/demo035",
    redditScore: 18,
    numComments: 10,
  },
  {
    id: "seed-036",
    createdAt: "2026-02-22T16:50:00.000Z",
    subreddit: "army",
    author: "PERSEC_reminder",
    title: "Stop posting patches and unit identifiers in dating apps",
    body: "General FP awareness — references Hood area.",
    permalink: "/r/army/comments/demo036",
    redditScore: 400,
    numComments: 90,
  },
  {
    id: "seed-037",
    createdAt: "2026-02-24T19:00:00.000Z",
    subreddit: "texas",
    author: "weather_and_noise",
    title: "Thunder vs artillery debate — Bell County",
    body: "Humor thread; some serious sound ranging comments.",
    permalink: "/r/texas/comments/demo037",
    redditScore: 200,
    numComments: 88,
  },
  {
    id: "seed-038",
    createdAt: "2026-02-26T10:22:00.000Z",
    subreddit: "CredibleDefense",
    author: "vip_support_pattern",
    title: "Open source indicators during distinguished visitor weeks",
    body: "Case study mentions Hood; discusses aggregation risk across benign posts.",
    permalink: "/r/CredibleDefense/comments/demo038",
    redditScore: 177,
    numComments: 44,
  },
  {
    id: "seed-039",
    createdAt: "2026-02-28T08:05:00.000Z",
    subreddit: "Killeen",
    author: "early_runner",
    title: "Coyotes or something else on Stillhouse?",
    body: "Off topic nature post.",
    permalink: "/r/Killeen/comments/demo039",
    redditScore: 6,
    numComments: 4,
  },
  {
    id: "seed-040",
    createdAt: "2026-03-01T12:30:00.000Z",
    subreddit: "FortHood",
    author: "installation_watch",
    title: "Unofficial heads-up: equipment movement sighting",
    body: "User claims timestamped video of column leaving motor pool area; may aid adversary pattern-of-life analysis if authentic.",
    permalink: "/r/FortHood/comments/demo040",
    redditScore: 47,
    numComments: 19,
  },
];
